checking for card match function created in object
MichaelPachec0/nodejs-project-night pull request #36
Opened 2022-06-01 16:12 UTC by SarahMelki

#25 created a class with methods to check for matching cards. There are a couple other methods that could be deleted based on who is tackling them like shuffleCards, canFlipCard and flipCard.

2022-06-01 19:19 UTC, JoeDravarol commented on public/app.js
> +    }
Thanks for explaning, that make a lot of sense now!

2022-06-01 23:12 UTC, r-Dev03 requested changes
The shuffleCards function is backend functionality and has already been implemented, besides that LGTM!

2022-06-02 01:41 UTC, jericashall commented
This looks good. Mire is working on the card flipping, so you can comment that section out. 

Can you explain this function
getCardType(card) {
        return card.getElementsByClassName('squirtle')[0].src;
    }
Should it always be checking 0 index instead of the cards index?

2022-06-02 07:11 UTC, SarahMelki commented
> This looks good. Mire is working on the card flipping, so you can comment that section out.
> 
> Can you explain this function getCardType(card) { return card.getElementsByClassName('squirtle')[0].src; } Should it always be checking 0 index instead of the cards index?

Yup, so since it's only one card grabbed from the top of the array, (we need to get the value from the front face + using a class for this value, which I think after the changes should be 'dance' not 'squirtle') hence it's the card at index 0.

2022-06-02 07:14 UTC, SarahMelki commented
I missed adding a function when I was saving my work from the draft file!! An important function for the mis-matched cards:

cardMismatch(card1, card2) {
        this.active = true;
        card1.classList.remove('visible');
        card2.classList.remove('visible');
        this.active = false;
    }

2022-06-03 00:48 UTC, jericashall requested changes
Remove the shuffle method since it's done on the backend and add the cardMismatch method that you comment. Otherwise looks good.

2022-06-03 06:01 UTC, SarahMelki commented
I did the required changes but not sure where all the red 'checks have failed' are coming from. I followed all the steps though 😨

2022-06-04 22:01 UTC, jericashall commented
Sarah I think you should close this pull request, make sure you've pulled the lasted committed changes into your repository and then open another pull request.

2022-06-04 22:08 UTC, MichaelPachec0 commented
> I did the required changes but not sure where all the red 'checks have failed' are coming from. I followed all the steps though 😨

Sorry for not being too active, I'll try and see what I can do on getting this PR ready to merge.

2022-06-04 23:34 UTC, MichaelPachec0 commented
@SarahMelki i have kept both your pr's code and current. this should be ready for review now.

2022-06-06 01:01 UTC, jericashall approved these changes

2022-06-06 04:48 UTC, r-Dev03 approved these changes
LGTM!

2022-06-06 05:17 UTC, MichaelPachec0 approved these changes
Alright, more than happy to commit  seeing the rest of the group approves.

2022-06-06 05:17 UTC, merged